require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "vendor/**/*"

# Enabled and enforced by standard
Style/StringLiterals:
  Enabled: false

# Enabled and enforced by standard
Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

# Enabled and enforced by standard
Style/EmptyMethod:
  Enabled: false

# Enabled and enforced by standard
Layout/ArgumentAlignment:
  Enabled: false

# Enabled and enforced by standard
Style/TernaryParentheses:
  Enabled: false

# Enabled and enforced by standard
Style/HashSyntax:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always_true

# Disabled as in standard
Style/Documentation:
  Enabled: false

# Disabled as in standard
Bundler/OrderedGems:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: brackets

Style/WordArray:
  Enabled: true
  EnforcedStyle: brackets

# Disabled as in standard
Lint/EmptyBlock:
  Enabled: false

# Disabled as in standard
Metrics/BlockLength:
  Enabled: false

# Disabled as in standard
Layout/LineLength:
  Enabled: false

Naming/VariableNumber:
  Enabled: true
  EnforcedStyle: snake_case

Naming/FileName:
  Enabled: true
  Exclude:
    - "spec/support/shoulda-matchers.rb"
