name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * 6"

env:
  CI: "yes"

jobs:
  rspec:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: bootsnap precompile
        run: bundle exec bootsnap precompile --gemfile app/ lib/
      - name: rails zeitwerk:check
        run: bundle exec rails zeitwerk:check
      - name: rails db:create
        run: bundle exec rails db:create
      - name: rails db:migrate
        run: bundle exec rails db:migrate
      - name: Run tests
        run: bundle exec rspec --force-color --profile --format documentation
