name: RSpec

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 21 * * 6"

env:
  CI: "yes"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  POSTGRES_USER: "runner"
  POSTGRES_DB: "cars_test"
  PGHOST: "localhost"

jobs:
  rspec:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: "postgres:15.1"
        env:
          POSTGRES_HOST_AUTH_METHOD: "trust"
          POSTGRES_USER: "runner"
          POSTGRES_DB: "cars_test"
        ports:
          - "5432:5432"
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup setup-chromedriver
        uses: nanasess/setup-chromedriver@v1.1.0
      - name: bootsnap precompile
        run: bundle exec bootsnap precompile --gemfile app/ lib/
      - run: bin/rails zeitwerk:check
      - run: cp -f config/database.yml.ci config/database.yml
      - run: bin/rails db:create
      - run: bin/rails db:migrate
      - name: Run tests
        run: |
          chromedriver --version
          export DISPLAY=:99
          chromedriver --url-base=/wd/hub &
          sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional
          bundle exec rspec --force-color --profile --format documentation
